routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\LoginController;
use App\Http\Controllers\RegisterController;
use App\Http\Controllers\AdminDesaController;
use App\Http\Controllers\PerangkatController;
use App\Http\Controllers\EditorController;
use App\Http\Controllers\BlogController;
use App\Http\Controllers\ViewController;
use App\Http\Controllers\PeraturanController;
use App\Http\Controllers\PengumumanController;
use App\Http\Controllers\ProfilController;
use App\Models\Blog;
use App\Models\Peraturan;
use App\Models\Pengumuman;
use Illuminate\Support\Facades\DB;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    $blog = Blog::latest()->paginate(3);
    $peraturan = Peraturan::orderBy('id')->get();
    $pengumuman = Pengumuman::latest()->paginate(6);
    return view('beranda.utama', [
        'blogs' => $blog,
        'peraturans' => $peraturan,
        'pengumumans' => $pengumuman
    ]);
});

Route::get('/regulasi', function () {
    $peraturan = Peraturan::orderBy('id')->get();
    return view('beranda.regulasi', [
        'peraturans' => $peraturan
    ]);
});

//Profil Desa
Route::resource('profil', ProfilController::class);
// Route::get('/pilihdesa', [ProfilController::class, 'pilihdesa']);
Route::post('/profil/lihatprofil', [ProfilController::class, 'lihatprofil']);
Route::post('/getDesa', [ProfilController::class, 'getDesa']);

Route::get('/view/{id}', [ViewController::class, 'lihat']);
Route::get('/viewperaturan/{id}', [ViewController::class, 'lihatperaturan']);
Route::get('/viewpengumuman/{id}', [ViewController::class, 'lihatpengumuman']);


Route::post('/masuk', [LoginController::class, 'cekMasuk']);
Route::get('/login', function () {
    return view('beranda.login');
});

Route::group(['middleware' => ['AuthDesa']], function () {

    Route::get('/adminDesa', [AdminDesaController::class, 'index']);
    Route::post('/logoutDesa', [AdminDesaController::class, 'logout']);
    Route::get('/logoutDesa', [AdminDesaController::class, 'logout']);
    Route::get('/adminDesa/formKewilayahan', [AdminDesaController::class, 'formKewilayahan']);
    Route::post('/adminDesa/tambahDatumWil', [AdminDesaController::class, 'tambahDatumWil']);
    Route::post('/adminDesa/updateDatumWil', [AdminDesaController::class, 'updateDatumWil']);

    Route::get('/adminDesa/formPerangkat', [PerangkatController::class, 'formPerangkat']);
    Route::post('/adminDesa/tambahDatumPer', [PerangkatController::class, 'tambahDatumPer']);
    Route::post('/adminDesa/updateDatumPer', [PerangkatController::class, 'updateDatumPer']);
    Route::post('/adminDesa/copyDatumPer', [PerangkatController::class, 'copyDatumPer']);
});

Route::group(['middleware' => ['AuthEditor']], function () {
    Route::get('/editor', [EditorController::class, 'index']);
    Route::post('/logoutEditor', [EditorController::class, 'logoutEditor']);
    Route::get('/logoutEditor', [EditorController::class, 'logoutEditor']);
    Route::resource('blog', BlogController::class);
    Route::resource('peraturan', PeraturanController::class);
    Route::resource('pengumuman', PengumumanController::class);
});


Route::get('/register', [RegisterController::class, 'index']);
Route::get('/register/tambah', [RegisterController::class, 'formTambah']);
Route::post('/register/store', [RegisterController::class, 'store']);
Route::post('/register/delete/{data}', [RegisterController::class, 'delete']);

app/Models/Pengumuman.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Pengumuman extends Model
{
    use HasFactory;

    /**
     * fillable
     *
     * @var array
     */
    public $table = "pengumumans";
    protected $fillable = [
        'title', 'content'
    ];
}

app/Http/Controllers/EditorController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Storage;
use App\Models\Admin;
use App\Models\Post;
use App\Models\Blog;
use App\Models\Pengumuman;


class EditorController extends Controller
{

    public function index()
    {
        $infos = Admin::where('id', session('loggedEditor'))->first();

        return view('editor.index', [
            'infos' => $infos,

        ]);
    }

    public function logoutEditor(Request $request)
    {
        if (session()->has('loggedEditor')) {
            session()->pull('loggedEditor');
            session()->pull('loggedAdmin');
            $request->session()->invalidate();

            $request->session()->regenerateToken();
            return redirect('/');
        }
    }


    public function berita()
    {
        $infos = Admin::where('id', session('loggedEditor'))->first();
        $berita = Post::select('*')->get();
        return view('editor.berita.index', [
            'infos' => $infos,
            'beritas' => $berita

        ]);
    }

    public function blog()
    {
        $infos = Admin::where('id', session('loggedEditor'))->first();
        $blog = Blog::select('*')->get();
        return view('editor.blog.index', [
            'infos' => $infos,
            'blog' => $blog

        ]);
    }

    public function create()
    {
        return view('blog.create',);
    }

    public function store(Request $request)
    {
        $this->validate($request, [
            'image'     => 'required|image|mimes:png,jpg,jpeg',
            'title'     => 'required',
            'content'   => 'required'
        ]);

        //upload image
        $image = $request->file('image');
        $image->storeAs('public/blogs', $image->hashName());

        $blog = Blog::create([
            'image'     => $image->hashName(),
            'title'     => $request->title,
            'content'   => $request->content
        ]);

        if ($blog) {
            //redirect dengan pesan sukses
            return redirect()->route('blog.index')->with(['success' => 'Data Berhasil Disimpan!']);
        } else {
            //redirect dengan pesan error
            return redirect()->route('blog.index')->with(['error' => 'Data Gagal Disimpan!']);
        }
    }

    /**
     * edit
     *
     * @param  mixed $blog
     * @return void
     */
    public function edit(Blog $blog)
    {
        return view('blog.edit', compact('blog'));
    }

    /**
     * update
     *
     * @param  mixed $request
     * @param  mixed $blog
     * @return void
     */
    public function update(Request $request, Blog $blog)
    {
        $this->validate($request, [
            'title'     => 'required',
            'content'   => 'required'
        ]);

        //get data Blog by ID
        $blog = Blog::findOrFail($blog->id);

        if ($request->file('image') == "") {

            $blog->update([
                'title'     => $request->title,
                'content'   => $request->content
            ]);
        } else {

            //hapus old image
            Storage::disk('local')->delete('public/blogs/' . $blog->image);

            //upload new image
            $image = $request->file('image');
            $image->storeAs('public/blogs', $image->hashName());

            $blog->update([
                'image'     => $image->hashName(),
                'title'     => $request->title,
                'content'   => $request->content
            ]);
        }

        if ($blog) {
            //redirect dengan pesan sukses
            return redirect()->route('blog.index')->with(['success' => 'Data Berhasil Diupdate!']);
        } else {
            //redirect dengan pesan error
            return redirect()->route('blog.index')->with(['error' => 'Data Gagal Diupdate!']);
        }
    }

    /**
     * destroy
     *
     * @param  mixed $id
     * @return void
     */
    public function destroy($id)
    {
        $blog = Blog::findOrFail($id);
        $blog->delete();

        if ($blog) {
            //redirect dengan pesan sukses
            return redirect()->route('blog.index')->with(['success' => 'Data Berhasil Dihapus!']);
        } else {
            //redirect dengan pesan error
            return redirect()->route('blog.index')->with(['error' => 'Data Gagal Dihapus!']);
        }
    }
}

app/Http/Controllers/PengumumanController.php
<?php

namespace App\Http\Controllers;

use App\Models\Pengumuman;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Storage;
use App\Models\Admin;
use Illuminate\Support\Facades\DB;


class PengumumanController extends Controller
{
    /**
     * index
     *
     * @return void
     */
    public function index()
    {
        $pengumumans = Pengumuman::latest()->paginate(5);
        $infos = Admin::where('id', session('loggedEditor'))->first();
        return view('editor.pengumuman.index',  [
            'infos' => $infos,
            'pengumumans' => $pengumumans
        ]);
    }

    /**
     * create
     *
     * @return void
     */
    public function create()
    {
        return view('editor.pengumuman.create');
    }

    /**
     * store
     *
     * @param  mixed $request
     * @return void
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'title'     => 'required',
            'nomor'     => 'max:3',
            'tahun'     => 'max:4',
        ]);


        $pengumuman = Pengumuman::create([
            'title'     => $request->title,
            'nomor'     => $request->nomor,
            'tahun'     => $request->tahun,
        ]);

        if ($pengumuman) {
            //redirect dengan pesan sukses
            return redirect()->route('pengumuman.index')->with(['success' => 'Data Berhasil Disimpan!']);
        } else {
            //redirect dengan pesan error
            return redirect()->route('pengumuman.index')->with(['error' => 'Data Gagal Disimpan!']);
        }
    }

    /**
     * edit
     *
     * @param  mixed $blog
     * @return void
     */
    public function edit(Pengumuman $pengumuman)
    {
        return view('editor.pengumuman.edit', compact('pengumuman'));
    }

    /**
     * update
     *
     * @param  mixed $request
     * @param  mixed $blog
     * @return void
     */
    public function update(Request $request, Pengumuman $pengumuman)
    {
        $this->validate($request, [
            'title'     => 'required',
            'nomor'     => 'max:3',
            'tahun'     => 'max:4',
        ]);

        //get data Blog by ID
        $pengumuman = Pengumuman::findOrFail($pengumuman->id);

        $pengumuman->update([
            'title'     => $request->title,
            'nomor'     => $request->nomor,
            'tahun'     => $request->tahun,
        ]);


        if ($pengumuman) {
            //redirect dengan pesan sukses
            return redirect()->route('pengumuman.index')->with(['success' => 'Data Berhasil Diupdate!']);
        } else {
            //redirect dengan pesan error
            return redirect()->route('pengumuman.index')->with(['error' => 'Data Gagal Diupdate!']);
        }
    }

    /**
     * destroy
     *
     * @param  mixed $id
     * @return void
     */
    public function destroy($id)
    {
        $pengumuman = Pengumuman::findOrFail($id);
        $pengumuman->delete();

        if ($pengumuman) {
            //redirect dengan pesan sukses
            return redirect()->route('pengumuman.index')->with(['success' => 'Data Berhasil Dihapus!']);
        } else {
            //redirect dengan pesan error
            return redirect()->route('pengumuman.index')->with(['error' => 'Data Gagal Dihapus!']);
        }
    }
}

resources/views/editor/pengumuman/create.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
</head>
<body style="background: lightgray">

    <div class="container mt-5 mb-5">
        <div class="row">
            <div class="col-md-12">
                <div class="card border-0 shadow rounded">
                    <div class="card-body">
                        <form action="{{ route('pengumuman.store') }}" method="POST" enctype="multipart/form-data">
                        
                            @csrf

                            <div class="form-group">
                                <label class="font-weight-bold">GAMBAR</label>
                                <input type="file" class="form-control @error('image') is-invalid @enderror" name="image">
                            
                                <!-- error message untuk title -->
                                @error('image')
                                    <div class="alert alert-danger mt-2">
                                        {{ $message }}
                                    </div>
                                @enderror
                            </div>

                            <div class="form-group">
                                <label class="font-weight-bold">JUDUL</label>
                                <input type="text" class="form-control @error('title') is-invalid @enderror" name="title" value="{{ old('title') }}" placeholder="Masukkan Judul Peraturan">
                            
                                <!-- error message untuk title -->
                                @error('title')
                                    <div class="alert alert-danger mt-2">
                                        {{ $message }}
                                    </div>
                                @enderror
                            </div>

                            <div class="form-group">
                                <label class="font-weight-bold">NOMOR</label>
                                <input type="text" class="form-control @error('nomor') is-invalid @enderror" name="nomor" value="{{ old('nomor') }}" placeholder="Masukkan Nomor Peraturan">
                            
                                <!-- error message untuk title -->
                                @error('nomor')
                                    <div class="alert alert-danger mt-2">
                                        {{ $message }}
                                    </div>
                                @enderror
                            </div>

                            <div class="form-group">
                                <label class="font-weight-bold">TAHUN</label>
                                <input type="text" class="form-control @error('tahun') is-invalid @enderror" name="tahun" value="{{ old('tahun') }}" placeholder="Masukkan Tahun Peraturan">
                            
                                <!-- error message untuk title -->
                                @error('tahun')
                                    <div class="alert alert-danger mt-2">
                                        {{ $message }}
                                    </div>
                                @enderror
                            </div>

                            <button type="submit" class="btn btn-md btn-primary">SIMPAN</button>
                            <button type="reset" class="btn btn-md btn-warning">RESET</button>

                        </form> 
                    </div>
                </div>
            </div>
        </div>
    </div>
    
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
<script src="https://cdn.ckeditor.com/4.13.1/standard/ckeditor.js"></script>
<script>
    CKEDITOR.replace( 'content' );
</script>
</body>
</html>

resources/views/editor/pengumuman/edit.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Edit Data Blog - SantriKoding.com</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
</head>
<body style="background: lightgray">

    <div class="container mt-5 mb-5">
        <div class="row">
            <div class="col-md-12">
                <div class="card border-0 shadow rounded">
                    <div class="card-body">
                        <form action="{{ route('pengumuman.update', $pengumuman->id) }}" method="POST" enctype="multipart/form-data">
                        
                            @csrf
                            @method('PUT')

                            <div class="form-group">
                                <label class="font-weight-bold">GAMBAR</label>
                                <input type="file" class="form-control" name="image">
                            </div>

                            <div class="form-group">
                                <label class="font-weight-bold">JUDUL</label>
                                <input type="text" class="form-control @error('title') is-invalid @enderror" name="title" value="{{ old('title', $pengumuman->title) }}" placeholder="Masukkan Judul Blog">
                            
                                <!-- error message untuk title -->
                                @error('title')
                                    <div class="alert alert-danger mt-2">
                                        {{ $message }}
                                    </div>
                                @enderror
                            </div>

                            <div class="form-group">
                                <label class="font-weight-bold">NOMOR</label>
                                <input type="text" class="form-control @error('nomor') is-invalid @enderror" name="nomor" value="{{ old('nomor', $pengumuman->nomor) }}" placeholder="Masukkan Nomor Peraturan">
                            
                                <!-- error message untuk title -->
                                @error('nomor')
                                    <div class="alert alert-danger mt-2">
                                        {{ $message }}
                                    </div>
                                @enderror
                            </div>

                            <div class="form-group">
                                <label class="font-weight-bold">TAHUN</label>
                                <input type="text" class="form-control @error('tahun') is-invalid @enderror" name="tahun" value="{{ old('tahun', $pengumuman->tahun) }}" placeholder="Masukkan Tahun Peraturan">
                            
                                <!-- error message untuk title -->
                                @error('tahun')
                                    <div class="alert alert-danger mt-2">
                                        {{ $message }}
                                    </div>
                                @enderror
                            </div>

                            <button type="submit" class="btn btn-md btn-primary">UPDATE</button>
                            <button type="reset" class="btn btn-md btn-warning">RESET</button>

                        </form> 
                    </div>
                </div>
            </div>
        </div>
    </div>
    
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
<script src="https://cdn.ckeditor.com/4.13.1/standard/ckeditor.js"></script>
<script>
    CKEDITOR.replace( 'content' );
</script>
</body>
</html>

resources/views/editor/pengumuman/index.blade.php
@extends('editor.templates.main')

@section('content')
    <br>
    <br>
    <div class="container mt-5">
        <div class="row">
            <div class="col-md-12">
                <div class="card border-0 shadow rounded">
                    <div class="card-body">
                        <a href="{{ route('pengumuman.create') }}" class="btn btn-md btn-success mb-3">TAMBAH PERATURAN</a>
                        <table class="table table-bordered">
                            <thead>
                              <tr>
                                <th scope="col">JUDUL</th>
                                <th scope="col">CONTENT</th>
                                <th scope="col">AKSI</th>
                              </tr>
                            </thead>
                            <tbody>
                              @forelse ($pengumumans as $pengumuman)
                                <tr>
                                    <td>{{ $pengumuman->title }}</td>
                                    <td>{!! Str::limit($pengumuman->content, 150) !!}</td>
                                    <td class="text-center">
                                        <form onsubmit="return confirm('Apakah Anda Yakin ?');" action="{{ route('pengumuman.destroy', $pengumuman->id) }}" method="POST">
                                            <a href="{{ route('pengumuman.edit', $pengumuman->id) }}" class="btn btn-sm btn-primary">EDIT</a>
                                            @csrf
                                            @method('DELETE')
                                            <button type="submit" class="btn btn-sm btn-danger">HAPUS</button>
                                        </form>
                                        
                                    </td>
                                </tr>
                              @empty
                                  <div class="alert alert-danger">
                                      Data Blog belum Tersedia.
                                  </div>
                              @endforelse
                            </tbody>
                          </table>  
                    </div>
                    <div class="footer">
                        {{ $pengumumans->links() }}
                        </div>
                </div>
                
                
            </div>
        </div>
    </div>


    <script>
        //message with toastr
        @if(session()-> has('success'))
        
            toastr.success('{{ session('success') }}', 'BERHASIL!'); 

        @elseif(session()-> has('error'))

            toastr.error('{{ session('error') }}', 'GAGAL!'); 
            
        @endif
    </script>

</body>

@endsection